DWAPlannerROS:
  max_vel_trans: 0.3
  min_vel_trans: 0.05
  max_vel_x: 0.3
  min_vel_x: 0.0
  max_vel_theta: 0.8
  min_vel_theta: 0.05         # 🔽 rotazioni più morbide e precise

  acc_lim_x: 1.5
  acc_lim_theta: 3.0

  yaw_goal_tolerance: 0.4     # 🔼 più tolleranza angolare
  xy_goal_tolerance: 0.4
  latch_xy_goal_tolerance: false

  sim_time: 1.2               # 🔽 traiettorie più corte → meno curve larghe
  sim_granularity: 0.025
  vx_samples: 20
  vtheta_samples: 40
  controller_frequency: 10.0

  path_distance_bias: 20.0
  goal_distance_bias: 18.0
  occdist_scale: 0.5

  forward_point_distance: 0.2
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.5

  oscillation_reset_dist: 0.05
  prune_plan: true
