local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  rolling_window: true
  update_frequency: 5.0
  publish_frequency: 2.0
  width: 6.0
  height: 6.0
  resolution: 0.05
  transform_tolerance: 0.5

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 3.0
  observation_sources: scan
  scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
  track_unknown_space: false

inflation_layer:
  inflation_radius: 0.55
  cost_scaling_factor: 3.5
